Algoritmo "semnome"
// 
//  
// Descrição   :Calculo da área do losango
// Autor(a)    : Rodrigo
// Data do dia que foi feito  : 12/03/2021
Var
diagonalmenor,diagonalMaior,area: real


Inicio
escreval("digite a diagonal menor")
leia(diagonalmenor)
escreval("digite a diagonal maior")
leia(diagonalMaior)

area <- (diagonalmenor*diagonalMaior)/2

escreval("area do losango e : ",area,"m2")

Fimalgoritmo