Algoritmo "areatrianguloretangulo"
// funcao: cacular area do rentanglo
//Autor: Rodrigo
// Data que foi feito : 02/03/2021
Var
 area,base,altura: real


Inicio

escreval("digite a base do triangulo")
leia(base)

escreval("digite a altura do triangulo")
leia(altura)

//Processamento

area <- (base*altura)/2


//saida

escreval("area do triangulo rentangulo e : ",area,"m2")



Fimalgoritmo